<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\Pcre\\' => array($vendorDir . '/composer/pcre/src'),
);
